/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelerRouteImport } from './routes/traveler'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HostRouteImport } from './routes/host'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TravelerSettingsRouteImport } from './routes/traveler.settings'
import { Route as TravelerProfileRouteImport } from './routes/traveler.profile'
import { Route as TravelerMessagesRouteImport } from './routes/traveler.messages'
import { Route as TravelerFavoritesRouteImport } from './routes/traveler.favorites'
import { Route as TravelerDashboardRouteImport } from './routes/traveler.dashboard'
import { Route as TravelerBookingsRouteImport } from './routes/traveler.bookings'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as HostSubscriptionRouteImport } from './routes/host.subscription'
import { Route as HostRoomsRouteImport } from './routes/host.rooms'
import { Route as HostReviewsRouteImport } from './routes/host.reviews'
import { Route as HostRevenueRouteImport } from './routes/host.revenue'
import { Route as HostReservationsRouteImport } from './routes/host.reservations'
import { Route as HostPropertyRouteImport } from './routes/host.property'
import { Route as HostMessagesRouteImport } from './routes/host.messages'
import { Route as HostDashboardRouteImport } from './routes/host.dashboard'
import { Route as HostCalendarRouteImport } from './routes/host.calendar'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as BookingConfirmationRouteImport } from './routes/booking.confirmation'

const TravelerRoute = TravelerRouteImport.update({
  id: '/traveler',
  path: '/traveler',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelerSettingsRoute = TravelerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TravelerRoute,
} as any)
const TravelerProfileRoute = TravelerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TravelerRoute,
} as any)
const TravelerMessagesRoute = TravelerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TravelerRoute,
} as any)
const TravelerFavoritesRoute = TravelerFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => TravelerRoute,
} as any)
const TravelerDashboardRoute = TravelerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TravelerRoute,
} as any)
const TravelerBookingsRoute = TravelerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => TravelerRoute,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSubscriptionRoute = HostSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => HostRoute,
} as any)
const HostRoomsRoute = HostRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => HostRoute,
} as any)
const HostReviewsRoute = HostReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => HostRoute,
} as any)
const HostRevenueRoute = HostRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => HostRoute,
} as any)
const HostReservationsRoute = HostReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => HostRoute,
} as any)
const HostPropertyRoute = HostPropertyRouteImport.update({
  id: '/property',
  path: '/property',
  getParentRoute: () => HostRoute,
} as any)
const HostMessagesRoute = HostMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => HostRoute,
} as any)
const HostDashboardRoute = HostDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HostRoute,
} as any)
const HostCalendarRoute = HostCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HostRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking/confirmation',
  path: '/booking/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/search': typeof SearchRoute
  '/traveler': typeof TravelerRouteWithChildren
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/host/calendar': typeof HostCalendarRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/messages': typeof HostMessagesRoute
  '/host/property': typeof HostPropertyRoute
  '/host/reservations': typeof HostReservationsRoute
  '/host/revenue': typeof HostRevenueRoute
  '/host/reviews': typeof HostReviewsRoute
  '/host/rooms': typeof HostRoomsRoute
  '/host/subscription': typeof HostSubscriptionRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/traveler/bookings': typeof TravelerBookingsRoute
  '/traveler/dashboard': typeof TravelerDashboardRoute
  '/traveler/favorites': typeof TravelerFavoritesRoute
  '/traveler/messages': typeof TravelerMessagesRoute
  '/traveler/profile': typeof TravelerProfileRoute
  '/traveler/settings': typeof TravelerSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/search': typeof SearchRoute
  '/traveler': typeof TravelerRouteWithChildren
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/host/calendar': typeof HostCalendarRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/messages': typeof HostMessagesRoute
  '/host/property': typeof HostPropertyRoute
  '/host/reservations': typeof HostReservationsRoute
  '/host/revenue': typeof HostRevenueRoute
  '/host/reviews': typeof HostReviewsRoute
  '/host/rooms': typeof HostRoomsRoute
  '/host/subscription': typeof HostSubscriptionRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/traveler/bookings': typeof TravelerBookingsRoute
  '/traveler/dashboard': typeof TravelerDashboardRoute
  '/traveler/favorites': typeof TravelerFavoritesRoute
  '/traveler/messages': typeof TravelerMessagesRoute
  '/traveler/profile': typeof TravelerProfileRoute
  '/traveler/settings': typeof TravelerSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/search': typeof SearchRoute
  '/traveler': typeof TravelerRouteWithChildren
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/host/calendar': typeof HostCalendarRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/messages': typeof HostMessagesRoute
  '/host/property': typeof HostPropertyRoute
  '/host/reservations': typeof HostReservationsRoute
  '/host/revenue': typeof HostRevenueRoute
  '/host/reviews': typeof HostReviewsRoute
  '/host/rooms': typeof HostRoomsRoute
  '/host/subscription': typeof HostSubscriptionRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/traveler/bookings': typeof TravelerBookingsRoute
  '/traveler/dashboard': typeof TravelerDashboardRoute
  '/traveler/favorites': typeof TravelerFavoritesRoute
  '/traveler/messages': typeof TravelerMessagesRoute
  '/traveler/profile': typeof TravelerProfileRoute
  '/traveler/settings': typeof TravelerSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/host'
    | '/search'
    | '/traveler'
    | '/booking/confirmation'
    | '/checkout/success'
    | '/host/calendar'
    | '/host/dashboard'
    | '/host/messages'
    | '/host/property'
    | '/host/reservations'
    | '/host/revenue'
    | '/host/reviews'
    | '/host/rooms'
    | '/host/subscription'
    | '/properties/$id'
    | '/property/$id'
    | '/traveler/bookings'
    | '/traveler/dashboard'
    | '/traveler/favorites'
    | '/traveler/messages'
    | '/traveler/profile'
    | '/traveler/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/host'
    | '/search'
    | '/traveler'
    | '/booking/confirmation'
    | '/checkout/success'
    | '/host/calendar'
    | '/host/dashboard'
    | '/host/messages'
    | '/host/property'
    | '/host/reservations'
    | '/host/revenue'
    | '/host/reviews'
    | '/host/rooms'
    | '/host/subscription'
    | '/properties/$id'
    | '/property/$id'
    | '/traveler/bookings'
    | '/traveler/dashboard'
    | '/traveler/favorites'
    | '/traveler/messages'
    | '/traveler/profile'
    | '/traveler/settings'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/host'
    | '/search'
    | '/traveler'
    | '/booking/confirmation'
    | '/checkout/success'
    | '/host/calendar'
    | '/host/dashboard'
    | '/host/messages'
    | '/host/property'
    | '/host/reservations'
    | '/host/revenue'
    | '/host/reviews'
    | '/host/rooms'
    | '/host/subscription'
    | '/properties/$id'
    | '/property/$id'
    | '/traveler/bookings'
    | '/traveler/dashboard'
    | '/traveler/favorites'
    | '/traveler/messages'
    | '/traveler/profile'
    | '/traveler/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  HostRoute: typeof HostRouteWithChildren
  SearchRoute: typeof SearchRoute
  TravelerRoute: typeof TravelerRouteWithChildren
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traveler': {
      id: '/traveler'
      path: '/traveler'
      fullPath: '/traveler'
      preLoaderRoute: typeof TravelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traveler/settings': {
      id: '/traveler/settings'
      path: '/settings'
      fullPath: '/traveler/settings'
      preLoaderRoute: typeof TravelerSettingsRouteImport
      parentRoute: typeof TravelerRoute
    }
    '/traveler/profile': {
      id: '/traveler/profile'
      path: '/profile'
      fullPath: '/traveler/profile'
      preLoaderRoute: typeof TravelerProfileRouteImport
      parentRoute: typeof TravelerRoute
    }
    '/traveler/messages': {
      id: '/traveler/messages'
      path: '/messages'
      fullPath: '/traveler/messages'
      preLoaderRoute: typeof TravelerMessagesRouteImport
      parentRoute: typeof TravelerRoute
    }
    '/traveler/favorites': {
      id: '/traveler/favorites'
      path: '/favorites'
      fullPath: '/traveler/favorites'
      preLoaderRoute: typeof TravelerFavoritesRouteImport
      parentRoute: typeof TravelerRoute
    }
    '/traveler/dashboard': {
      id: '/traveler/dashboard'
      path: '/dashboard'
      fullPath: '/traveler/dashboard'
      preLoaderRoute: typeof TravelerDashboardRouteImport
      parentRoute: typeof TravelerRoute
    }
    '/traveler/bookings': {
      id: '/traveler/bookings'
      path: '/bookings'
      fullPath: '/traveler/bookings'
      preLoaderRoute: typeof TravelerBookingsRouteImport
      parentRoute: typeof TravelerRoute
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/subscription': {
      id: '/host/subscription'
      path: '/subscription'
      fullPath: '/host/subscription'
      preLoaderRoute: typeof HostSubscriptionRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/rooms': {
      id: '/host/rooms'
      path: '/rooms'
      fullPath: '/host/rooms'
      preLoaderRoute: typeof HostRoomsRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/reviews': {
      id: '/host/reviews'
      path: '/reviews'
      fullPath: '/host/reviews'
      preLoaderRoute: typeof HostReviewsRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/revenue': {
      id: '/host/revenue'
      path: '/revenue'
      fullPath: '/host/revenue'
      preLoaderRoute: typeof HostRevenueRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/reservations': {
      id: '/host/reservations'
      path: '/reservations'
      fullPath: '/host/reservations'
      preLoaderRoute: typeof HostReservationsRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/property': {
      id: '/host/property'
      path: '/property'
      fullPath: '/host/property'
      preLoaderRoute: typeof HostPropertyRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/messages': {
      id: '/host/messages'
      path: '/messages'
      fullPath: '/host/messages'
      preLoaderRoute: typeof HostMessagesRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/dashboard': {
      id: '/host/dashboard'
      path: '/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof HostDashboardRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/calendar': {
      id: '/host/calendar'
      path: '/calendar'
      fullPath: '/host/calendar'
      preLoaderRoute: typeof HostCalendarRouteImport
      parentRoute: typeof HostRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/booking/confirmation': {
      id: '/booking/confirmation'
      path: '/booking/confirmation'
      fullPath: '/booking/confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface HostRouteChildren {
  HostCalendarRoute: typeof HostCalendarRoute
  HostDashboardRoute: typeof HostDashboardRoute
  HostMessagesRoute: typeof HostMessagesRoute
  HostPropertyRoute: typeof HostPropertyRoute
  HostReservationsRoute: typeof HostReservationsRoute
  HostRevenueRoute: typeof HostRevenueRoute
  HostReviewsRoute: typeof HostReviewsRoute
  HostRoomsRoute: typeof HostRoomsRoute
  HostSubscriptionRoute: typeof HostSubscriptionRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostCalendarRoute: HostCalendarRoute,
  HostDashboardRoute: HostDashboardRoute,
  HostMessagesRoute: HostMessagesRoute,
  HostPropertyRoute: HostPropertyRoute,
  HostReservationsRoute: HostReservationsRoute,
  HostRevenueRoute: HostRevenueRoute,
  HostReviewsRoute: HostReviewsRoute,
  HostRoomsRoute: HostRoomsRoute,
  HostSubscriptionRoute: HostSubscriptionRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

interface TravelerRouteChildren {
  TravelerBookingsRoute: typeof TravelerBookingsRoute
  TravelerDashboardRoute: typeof TravelerDashboardRoute
  TravelerFavoritesRoute: typeof TravelerFavoritesRoute
  TravelerMessagesRoute: typeof TravelerMessagesRoute
  TravelerProfileRoute: typeof TravelerProfileRoute
  TravelerSettingsRoute: typeof TravelerSettingsRoute
}

const TravelerRouteChildren: TravelerRouteChildren = {
  TravelerBookingsRoute: TravelerBookingsRoute,
  TravelerDashboardRoute: TravelerDashboardRoute,
  TravelerFavoritesRoute: TravelerFavoritesRoute,
  TravelerMessagesRoute: TravelerMessagesRoute,
  TravelerProfileRoute: TravelerProfileRoute,
  TravelerSettingsRoute: TravelerSettingsRoute,
}

const TravelerRouteWithChildren = TravelerRoute._addFileChildren(
  TravelerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  HostRoute: HostRouteWithChildren,
  SearchRoute: SearchRoute,
  TravelerRoute: TravelerRouteWithChildren,
  BookingConfirmationRoute: BookingConfirmationRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
