-- =============================================================================
-- Migration 0005 — Booking Engine
-- Scope : bookings, booking_guests, booking_events, booking_notes
--         + deferred FK from room_availability → bookings
--         + is_traveler_of_booking() SECURITY DEFINER helper
-- Depends on : 0001 (profiles, has_role, app_role)
--              0002 (billing.subscription_plans)
--              0003 (rooms, properties, host_profiles, is_host_of,
--                    app_cancellation_policy, app_host_status)
--              0004 (room_availability, claim_availability,
--                    release_availability)
-- Author: StayBF
-- =============================================================================

-- ============================================================
-- 1. ENUMS
-- ============================================================

-- Full booking state machine per Revenue doc §3.1 and Blueprint §0.1.
-- Terminal states: all cancelled_*, no_show.
-- Quasi-terminal: completed (can move to disputed); disputed can
-- resolve back to completed or to cancelled_by_system.
CREATE TYPE public.app_booking_status AS ENUM (
  'pending_payment',       -- booking created; availability held; awaiting payment
  'payment_processing',    -- payment attempt in flight at provider
  'awaiting_host',         -- payment held; host has 24h to accept (Request-to-Book)
  'confirmed',             -- payment captured; host accepted (or Instant Book)
  'checked_in',            -- arrival recorded; stay in progress
  'completed',             -- stay ended 24h+ ago; no active dispute
  'cancelled_by_traveler', -- traveler cancelled; policy-based refund
  'cancelled_by_host',     -- host cancelled; 100% refund + host strike
  'cancelled_by_system',   -- timeout, payment failure, or platform action
  'no_show',               -- host declared no-show within 24h of check_in
  'disputed'               -- dispute opened ≤72h after completed
);

CREATE TYPE public.app_payout_status AS ENUM (
  'pending',    -- booking completed; payout not yet batched
  'scheduled',  -- included in a payout batch
  'paid',       -- disbursed to host
  'on_hold',    -- frozen by dispute or KYC issue
  'reversed'    -- clawback applied after chargeback or fraud
);

-- Named event types for the append-only booking_events audit trail.
CREATE TYPE public.app_booking_event_type AS ENUM (
  'booking_created',
  'payment_initiated',
  'payment_succeeded',
  'payment_failed',
  'awaiting_host',
  'host_accepted',
  'host_declined',
  'booking_confirmed',
  'checked_in',
  'completed',
  'cancelled_by_traveler',
  'cancelled_by_host',
  'cancelled_by_system',
  'no_show_declared',
  'dispute_opened',
  'dispute_resolved_host',
  'dispute_resolved_traveler',
  'payout_scheduled',
  'payout_paid',
  'refund_initiated',
  'refund_completed'
);


-- ============================================================
-- 2. SECURITY-DEFINER HELPER: is_traveler_of_booking
-- ============================================================
-- Used by booking_guests and booking_events RLS SELECT policies
-- to avoid subqueries that would re-evaluate RLS on bookings
-- recursively.  Follows the same hardening pattern as has_role()
-- and is_host_of().

CREATE OR REPLACE FUNCTION public.is_traveler_of_booking(
  _user_id    uuid,
  _booking_id uuid
)
  RETURNS boolean
  LANGUAGE sql
  SECURITY DEFINER
  STABLE
  PARALLEL SAFE
  SET search_path = ''
AS $$
  SELECT CASE
    WHEN _user_id IS NULL OR _booking_id IS NULL THEN false
    ELSE EXISTS (
      SELECT 1
      FROM public.bookings b
      WHERE b.id          = _booking_id
        AND b.traveler_id = _user_id
    )
  END;
$$;

GRANT EXECUTE ON FUNCTION public.is_traveler_of_booking(uuid, uuid)
  TO authenticated;


-- ============================================================
-- 3. BOOKINGS
-- ============================================================
-- Central transaction record.  Financial columns (accommodation_amount
-- through host_payout_amount) are frozen at transition to 'confirmed'
-- and must never be updated afterwards.  The CHECK constraints below
-- encode the revenue model invariants from Revenue doc §1.2–1.3 at
-- the database layer so no code path can produce a mathematically
-- inconsistent booking.

CREATE TABLE IF NOT EXISTS public.bookings (
  id          uuid                    PRIMARY KEY DEFAULT extensions.gen_random_uuid(),

  -- Human-readable reference shown to both parties: STBF-XXXXXX
  -- Generated by the server function using Crockford base32.
  reference   text                    NOT NULL,

  traveler_id uuid                    NOT NULL,
  property_id uuid                    NOT NULL,
  room_id     uuid                    NOT NULL,

  -- Date range (check_out is the departure day — NOT a booked night)
  check_in    date                    NOT NULL,
  check_out   date                    NOT NULL,

  -- Computed and stored so reports can filter without recalculation
  nights      integer                 GENERATED ALWAYS AS (check_out - check_in) STORED,

  guests_adults   integer             NOT NULL DEFAULT 1,
  guests_children integer             NOT NULL DEFAULT 0,
  guests_infants  integer             NOT NULL DEFAULT 0,

  status      public.app_booking_status NOT NULL DEFAULT 'pending_payment',

  -- Snapshot of room.instant_book at booking creation time; determines
  -- which branch of the state machine is taken after payment.
  instant_book boolean                NOT NULL DEFAULT false,

  -- ── Financial snapshot ─────────────────────────────────────────────
  -- All amounts in integer FCFA.  Frozen at transition to 'confirmed'.
  -- service_fee_rate is always 0.1000 (Revenue doc §1.2).
  -- commission_rate is 0.1500 (free plan) or 0.0000 (paid plan),
  -- determined by host's active subscription at confirmation time
  -- (Revenue doc §1.3 snapshot rule).

  accommodation_amount    integer         NOT NULL,
  service_fee_rate        numeric(5,4)    NOT NULL DEFAULT 0.1000,
  service_fee_amount      integer         NOT NULL,
  commission_rate         numeric(5,4)    NOT NULL,
  commission_amount       integer         NOT NULL,
  total_amount            integer         NOT NULL,
  host_payout_amount      integer         NOT NULL,
  currency                text            NOT NULL DEFAULT 'XOF',

  -- Frozen subscription state used by payout and analytics.
  -- Shape: {plan_code, plan_id, period_end, commission_rate}
  host_subscription_snapshot jsonb        NOT NULL DEFAULT '{}'::jsonb,

  -- ── Cancellation ───────────────────────────────────────────────────
  -- Snapshot of property.cancellation_policy at booking creation time.
  cancellation_policy   public.app_cancellation_policy NOT NULL,
  cancellation_reason   text,
  cancelled_at          timestamptz,
  cancelled_by          uuid,           -- FK → profiles(id) ON DELETE SET NULL

  -- ── Payout tracking ────────────────────────────────────────────────
  payout_status public.app_payout_status NOT NULL DEFAULT 'pending',
  payout_id     uuid,                   -- FK → payouts(id) — set in Migration 0006

  -- ── Lifecycle timestamps ───────────────────────────────────────────
  confirmed_at  timestamptz,
  checked_in_at timestamptz,
  completed_at  timestamptz,
  created_at    timestamptz             NOT NULL DEFAULT now(),
  updated_at    timestamptz             NOT NULL DEFAULT now(),

  -- ── Constraints ────────────────────────────────────────────────────

  CONSTRAINT bookings_reference_unique UNIQUE (reference),

  CONSTRAINT bookings_dates_valid CHECK (check_out > check_in),
  CONSTRAINT bookings_nights_pos  CHECK ((check_out - check_in) > 0),

  CONSTRAINT bookings_guests_adults_pos    CHECK (guests_adults >= 1),
  CONSTRAINT bookings_guests_children_pos  CHECK (guests_children >= 0),
  CONSTRAINT bookings_guests_infants_pos   CHECK (guests_infants >= 0),

  -- Revenue model invariants (Revenue doc §1.2–1.3 + dev notes §2)
  CONSTRAINT bookings_service_fee_rate     CHECK (service_fee_rate = 0.1000),
  CONSTRAINT bookings_commission_rate_valid CHECK (
    commission_rate IN (0.0000, 0.1500)
  ),
  CONSTRAINT bookings_accommodation_pos    CHECK (accommodation_amount > 0),
  CONSTRAINT bookings_total_invariant      CHECK (
    total_amount = accommodation_amount + service_fee_amount
  ),
  CONSTRAINT bookings_payout_invariant     CHECK (
    host_payout_amount = accommodation_amount - commission_amount
  ),
  CONSTRAINT bookings_currency_xof         CHECK (currency = 'XOF'),

  -- Lifecycle timestamp consistency
  CONSTRAINT bookings_confirmed_at_consistency CHECK (
    (status = 'confirmed' AND confirmed_at IS NOT NULL)
    OR status != 'confirmed'
  ),
  CONSTRAINT bookings_completed_at_consistency CHECK (
    (status = 'completed' AND completed_at IS NOT NULL)
    OR status != 'completed'
  ),

  -- ── Foreign keys ───────────────────────────────────────────────────
  FOREIGN KEY (traveler_id)   REFERENCES public.profiles (id)     ON DELETE RESTRICT,
  FOREIGN KEY (property_id)   REFERENCES public.properties (id)   ON DELETE RESTRICT,
  FOREIGN KEY (room_id)       REFERENCES public.rooms (id)        ON DELETE RESTRICT,
  FOREIGN KEY (cancelled_by)  REFERENCES public.profiles (id)     ON DELETE SET NULL
  -- payout_id FK added in Migration 0006 after payouts table is created
);

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings FORCE ROW LEVEL SECURITY;

-- Traveler sees own bookings
CREATE POLICY "bookings: traveler read own"
  ON public.bookings
  FOR SELECT
  USING (traveler_id = auth.uid());

-- Host sees bookings on their properties
CREATE POLICY "bookings: host read own properties"
  ON public.bookings
  FOR SELECT
  USING (public.is_host_of(auth.uid(), property_id));

-- Support, finance, admin read-all
CREATE POLICY "bookings: support read-all"
  ON public.bookings
  FOR SELECT
  USING (public.has_role(auth.uid(), 'support'::public.app_role));

CREATE POLICY "bookings: finance read-all"
  ON public.bookings
  FOR SELECT
  USING (public.has_role(auth.uid(), 'finance'::public.app_role));

CREATE POLICY "bookings: admin all"
  ON public.bookings
  FOR ALL
  USING (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR public.has_role(auth.uid(), 'super_admin'::public.app_role)
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR public.has_role(auth.uid(), 'super_admin'::public.app_role)
  );

-- No INSERT policy for authenticated: all booking creation goes through
-- createBooking() server function which runs the availability claim,
-- pricing validation, and INSERT atomically as service_role.
-- No direct UPDATE for authenticated: all state transitions are
-- enforced by named server functions using service_role.
-- No DELETE policy: bookings are never deleted.

GRANT SELECT ON public.bookings TO authenticated;
GRANT ALL    ON public.bookings TO service_role;

-- Traveler dashboard: own bookings filtered by status
CREATE INDEX IF NOT EXISTS idx_bookings_traveler_status
  ON public.bookings (traveler_id, status);

-- Host dashboard and revenue reports
CREATE INDEX IF NOT EXISTS idx_bookings_property_dates
  ON public.bookings (property_id, check_in, check_out);

-- Availability conflict re-check at host accept time
CREATE INDEX IF NOT EXISTS idx_bookings_room_dates
  ON public.bookings (room_id, check_in, check_out);

-- Cron jobs targeting live (non-terminal) bookings
CREATE INDEX IF NOT EXISTS idx_bookings_live_status
  ON public.bookings (status, created_at)
  WHERE status NOT IN (
    'completed',
    'cancelled_by_traveler',
    'cancelled_by_host',
    'cancelled_by_system',
    'no_show'
  );

-- Lookup by human reference (support / email links)
CREATE INDEX IF NOT EXISTS idx_bookings_reference
  ON public.bookings (reference);

-- Payout batching job
CREATE INDEX IF NOT EXISTS idx_bookings_payout_pending
  ON public.bookings (payout_status, completed_at)
  WHERE payout_status = 'pending';

-- Hold-expiry cron: find unpaid bookings older than 15 minutes
CREATE INDEX IF NOT EXISTS idx_bookings_pending_payment_age
  ON public.bookings (created_at)
  WHERE status = 'pending_payment';

-- Revenue timeline on admin dashboard
CREATE INDEX IF NOT EXISTS idx_bookings_confirmed_at
  ON public.bookings (confirmed_at DESC)
  WHERE confirmed_at IS NOT NULL;

CREATE TRIGGER trg_bookings_updated_at
  BEFORE UPDATE ON public.bookings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- 4. DEFERRED FK: room_availability → bookings
-- ============================================================
-- Now that bookings exists, add the FK that was noted as deferred
-- in Migration 0004.

ALTER TABLE public.room_availability
  ADD CONSTRAINT fk_availability_booking
  FOREIGN KEY (booking_id)
  REFERENCES public.bookings (id)
  ON DELETE SET NULL;


-- ============================================================
-- 5. BOOKING_GUESTS
-- ============================================================
-- Point-in-time record of every person staying during a booking.
-- The lead guest (is_lead = true) mirrors the traveler who booked;
-- duplicated here so the record is immutable even if the profile
-- is later updated.  Document numbers are encrypted at app layer
-- (libsodium sealed box) before storage.

CREATE TABLE IF NOT EXISTS public.booking_guests (
  id              uuid        PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  booking_id      uuid        NOT NULL,
  full_name       text        NOT NULL,
  nationality     text,                      -- ISO-2 country code
  document_type   text,                      -- passport | cni | residence_permit
  -- Stored as app-layer libsodium sealed-box ciphertext; never in DTOs
  document_number text,
  date_of_birth   date,
  is_lead         boolean     NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT booking_guests_full_name_nonempty CHECK (length(trim(full_name)) > 0),

  FOREIGN KEY (booking_id) REFERENCES public.bookings (id) ON DELETE CASCADE
);

ALTER TABLE public.booking_guests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_guests FORCE ROW LEVEL SECURITY;

-- Exactly one lead guest per booking enforced at DB level
CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_guests_lead
  ON public.booking_guests (booking_id)
  WHERE is_lead = true;

-- Traveler reads own booking's guests
CREATE POLICY "booking_guests: traveler read own"
  ON public.booking_guests
  FOR SELECT
  USING (public.is_traveler_of_booking(auth.uid(), booking_id));

-- Host reads guests of bookings on their properties
CREATE POLICY "booking_guests: host read own"
  ON public.booking_guests
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.bookings b
      WHERE b.id = booking_id
        AND public.is_host_of(auth.uid(), b.property_id)
    )
  );

-- Support and admin read-all
CREATE POLICY "booking_guests: support read-all"
  ON public.booking_guests
  FOR SELECT
  USING (public.has_role(auth.uid(), 'support'::public.app_role));

CREATE POLICY "booking_guests: admin all"
  ON public.booking_guests
  FOR ALL
  USING (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR public.has_role(auth.uid(), 'super_admin'::public.app_role)
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR public.has_role(auth.uid(), 'super_admin'::public.app_role)
  );

-- INSERT via createBooking() / addGuest() server functions only
GRANT SELECT, INSERT ON public.booking_guests TO authenticated;
GRANT ALL            ON public.booking_guests TO service_role;

CREATE INDEX IF NOT EXISTS idx_booking_guests_booking
  ON public.booking_guests (booking_id);


-- ============================================================
-- 6. BOOKING_EVENTS
-- ============================================================
-- Append-only audit trail of every state transition in the booking
-- lifecycle.  One row per event; never updated or deleted.
-- Powers the admin timeline, dispute resolution, and compliance.
-- Separate from ops.audit_logs (platform-wide security log).

CREATE TABLE IF NOT EXISTS public.booking_events (
  id           uuid                          PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  booking_id   uuid                          NOT NULL,
  event_type   public.app_booking_event_type NOT NULL,
  from_status  public.app_booking_status,    -- NULL for the initial creation event
  to_status    public.app_booking_status     NOT NULL,
  actor_id     uuid,                         -- NULL for system-initiated events
  actor_role   public.app_role,              -- role held at time of event
  reason       text,                         -- required on cancellations / disputes
  metadata     jsonb,                        -- event-specific payload
  -- No updated_at: this table is append-only
  created_at   timestamptz                   NOT NULL DEFAULT now(),

  FOREIGN KEY (booking_id) REFERENCES public.bookings (id) ON DELETE CASCADE,
  FOREIGN KEY (actor_id)   REFERENCES public.profiles (id) ON DELETE SET NULL
);

ALTER TABLE public.booking_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_events FORCE ROW LEVEL SECURITY;

-- Traveler reads events on own bookings
CREATE POLICY "booking_events: traveler read own"
  ON public.booking_events
  FOR SELECT
  USING (public.is_traveler_of_booking(auth.uid(), booking_id));

-- Host reads events on bookings for their properties
CREATE POLICY "booking_events: host read own"
  ON public.booking_events
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.bookings b
      WHERE b.id = booking_id
        AND public.is_host_of(auth.uid(), b.property_id)
    )
  );

-- Support, finance, admin read-all
CREATE POLICY "booking_events: support read-all"
  ON public.booking_events
  FOR SELECT
  USING (public.has_role(auth.uid(), 'support'::public.app_role));

CREATE POLICY "booking_events: finance read-all"
  ON public.booking_events
  FOR SELECT
  USING (public.has_role(auth.uid(), 'finance'::public.app_role));

CREATE POLICY "booking_events: admin all"
  ON public.booking_events
  FOR ALL
  USING (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR public.has_role(auth.uid(), 'super_admin'::public.app_role)
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR public.has_role(auth.uid(), 'super_admin'::public.app_role)
  );

-- No INSERT for authenticated: all writes via server functions as service_role.
-- This enforces append-only semantics — no client path can manufacture or
-- delete event log entries.
GRANT SELECT ON public.booking_events TO authenticated;
GRANT ALL    ON public.booking_events TO service_role;

-- Full event timeline for a booking (admin view, traveler history)
CREATE INDEX IF NOT EXISTS idx_booking_events_booking_time
  ON public.booking_events (booking_id, created_at ASC);

-- Admin analytics: count transitions by type over time
CREATE INDEX IF NOT EXISTS idx_booking_events_type_time
  ON public.booking_events (event_type, created_at DESC);


-- ============================================================
-- 7. BOOKING_NOTES
-- ============================================================
-- Internal staff notes on a booking.  Not visible to travelers or
-- hosts.  Used during dispute resolution, fraud review, and CS.

CREATE TABLE IF NOT EXISTS public.booking_notes (
  id          uuid        PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
  booking_id  uuid        NOT NULL,
  author_id   uuid        NOT NULL,
  body        text        NOT NULL,
  is_pinned   boolean     NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT booking_notes_body_nonempty CHECK (length(trim(body)) > 0),

  FOREIGN KEY (booking_id) REFERENCES public.bookings (id)   ON DELETE CASCADE,
  FOREIGN KEY (author_id)  REFERENCES public.profiles (id)   ON DELETE RESTRICT
);

ALTER TABLE public.booking_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_notes FORCE ROW LEVEL SECURITY;

-- Support staff read and write own notes
CREATE POLICY "booking_notes: support all"
  ON public.booking_notes
  FOR ALL
  USING  (public.has_role(auth.uid(), 'support'::public.app_role))
  WITH CHECK (public.has_role(auth.uid(), 'support'::public.app_role));

-- Admin full access
CREATE POLICY "booking_notes: admin all"
  ON public.booking_notes
  FOR ALL
  USING (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR public.has_role(auth.uid(), 'super_admin'::public.app_role)
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR public.has_role(auth.uid(), 'super_admin'::public.app_role)
  );

-- Travelers and hosts have no access — internal only

GRANT SELECT, INSERT, UPDATE ON public.booking_notes TO authenticated;
GRANT ALL                    ON public.booking_notes TO service_role;

CREATE INDEX IF NOT EXISTS idx_booking_notes_booking
  ON public.booking_notes (booking_id, created_at DESC);

CREATE TRIGGER trg_booking_notes_updated_at
  BEFORE UPDATE ON public.booking_notes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- 8. TRIGGER: expire_pending_bookings (cron support)
-- ============================================================
-- Called by the nightly/5-minute cron job via service_role.
-- Releases availability and cancels bookings that have been in
-- 'pending_payment' for more than 15 minutes without a payment
-- being initiated.
--
-- Concurrency guard: the UPDATE on bookings uses
-- AND status = 'pending_payment' so that a booking that was
-- advanced to 'payment_processing' by a concurrent webhook between
-- the SELECT and the UPDATE is left untouched.
--
-- This function is NOT called on every row change — it is invoked
-- explicitly by the cron server function via:
--   SELECT public.expire_pending_bookings();

CREATE OR REPLACE FUNCTION public.expire_pending_bookings()
  RETURNS integer        -- number of bookings expired in this run
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = ''
AS $$
DECLARE
  v_booking   record;
  v_count     integer := 0;
  v_hold_mins integer := 15;
BEGIN
  FOR v_booking IN
    SELECT id
    FROM   public.bookings
    WHERE  status     = 'pending_payment'::public.app_booking_status
      AND  created_at < now() - (v_hold_mins || ' minutes')::interval
    LIMIT  100           -- batch: avoid long-lived transactions
  LOOP
    -- Release availability (idempotent if already released)
    PERFORM public.release_availability(v_booking.id);

    -- Cancel the booking only if it is still pending_payment.
    -- If a concurrent webhook has since advanced it, this UPDATE
    -- affects 0 rows and we leave it alone.
    UPDATE public.bookings
    SET    status               = 'cancelled_by_system'::public.app_booking_status,
           cancellation_reason  = 'payment_hold_expired',
           cancelled_at         = now(),
           updated_at           = now()
    WHERE  id     = v_booking.id
      AND  status = 'pending_payment'::public.app_booking_status;

    IF FOUND THEN
      INSERT INTO public.booking_events (
        booking_id, event_type,
        from_status, to_status,
        actor_id, reason, created_at
      ) VALUES (
        v_booking.id,
        'cancelled_by_system'::public.app_booking_event_type,
        'pending_payment'::public.app_booking_status,
        'cancelled_by_system'::public.app_booking_status,
        NULL,
        'payment_hold_expired',
        now()
      );

      v_count := v_count + 1;
    END IF;
  END LOOP;

  RETURN v_count;
END;
$$;

-- Only callable by server-side cron handler (service_role).
-- No GRANT to authenticated or anon.
GRANT EXECUTE ON FUNCTION public.expire_pending_bookings()
  TO service_role;


-- ============================================================
-- 9. TRIGGER: enforce booking state machine transitions
-- ============================================================
-- A BEFORE UPDATE trigger that rejects any status transition not in
-- the approved state machine.  This is the DB-layer backstop; the
-- server functions enforce business rules; this trigger enforces the
-- structural shape of allowed moves.
--
-- Invalid transitions raise SQLSTATE '23514' (check_violation)
-- with a descriptive message.

CREATE OR REPLACE FUNCTION public.validate_booking_transition()
  RETURNS trigger
  LANGUAGE plpgsql
  SET search_path = ''
AS $$
BEGIN
  -- No-op if status is not changing
  IF NEW.status = OLD.status THEN
    RETURN NEW;
  END IF;

  -- Allowed transition map
  IF NOT (
    -- From pending_payment
    (OLD.status = 'pending_payment'          AND NEW.status IN ('payment_processing', 'cancelled_by_system'))
    -- From payment_processing
    OR (OLD.status = 'payment_processing'    AND NEW.status IN ('awaiting_host', 'confirmed', 'cancelled_by_system'))
    -- From awaiting_host
    OR (OLD.status = 'awaiting_host'         AND NEW.status IN ('confirmed', 'cancelled_by_host', 'cancelled_by_system'))
    -- From confirmed
    OR (OLD.status = 'confirmed'             AND NEW.status IN ('checked_in', 'cancelled_by_traveler', 'cancelled_by_host', 'cancelled_by_system'))
    -- From checked_in
    OR (OLD.status = 'checked_in'            AND NEW.status IN ('completed', 'no_show', 'cancelled_by_system'))
    -- From completed (only dispute window)
    OR (OLD.status = 'completed'             AND NEW.status = 'disputed')
    -- From disputed (resolution)
    OR (OLD.status = 'disputed'              AND NEW.status IN ('completed', 'cancelled_by_system'))
  ) THEN
    RAISE EXCEPTION
      'Invalid booking status transition: % → % (booking_id: %)',
      OLD.status, NEW.status, OLD.id
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_booking_state_machine
  BEFORE UPDATE OF status ON public.bookings
  FOR EACH ROW
  EXECUTE FUNCTION public.validate_booking_transition();


-- =============================================================================
-- DOWN MIGRATION
-- =============================================================================
/*
  To roll back (execute in reverse dependency order):

  -- Remove deferred FK added to Migration 0004's table
  ALTER TABLE public.room_availability
    DROP CONSTRAINT IF EXISTS fk_availability_booking;

  DROP FUNCTION IF EXISTS public.expire_pending_bookings();
  DROP FUNCTION IF EXISTS public.validate_booking_transition();
  DROP FUNCTION IF EXISTS public.is_traveler_of_booking(uuid, uuid);

  DROP TABLE IF EXISTS public.booking_notes;
  DROP TABLE IF EXISTS public.booking_events;
  DROP TABLE IF EXISTS public.booking_guests;
  DROP TABLE IF EXISTS public.bookings;

  DROP TYPE IF EXISTS public.app_booking_event_type;
  DROP TYPE IF EXISTS public.app_payout_status;
  DROP TYPE IF EXISTS public.app_booking_status;
*/
